name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome

      - name: Merge reports
        if: always()
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json

      - name: Generate HTML report
        if: always()
        run: npx marge cypress/reports/report.json -f report -o cypress/reports/html

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html